name: wb
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.0+2
  flutter_swiper: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0
  image_test_utils: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/images/home_icon1b.png
  - lib/assets/images/home_icon1y.png
  - lib/assets/images/home_icon2b.png
  - lib/assets/images/home_icon2y.png
  - lib/assets/images/home_icon3b.png
  - lib/assets/images/home_icon3y.png
  - lib/assets/images/home_icon4b.png
  - lib/assets/images/home_icon4y.png
  - lib/assets/images/home_icon5b.png
  - lib/assets/images/home_icon5y.png
  - lib/assets/images/home_photograph.png
  - lib/assets/images/home_banner1.png